### PR TITLE
Improve start script for quest Vyletongue Corruption.

### PR DESCRIPTION
**Pull request by miraco**
Based on https://github.com/vmangos/core/blob/1f4e6bab879e309da5b4a3911047abfb9f3c4b02/sql/migrations/20211202023408_world.sql

We dont have SCRIPT_COMMAND_TURN_TO with orientation, used normal move with spawn coords for it. SCRIPT_COMMAND_SET_FACING Turn resulting source to resulting target.

https://user-images.githubusercontent.com/19734826/144726650-e493a188-04a6-451b-8c79-6241ed97c796.png
@AnonXS can maybe mark next field in yellow :D

### CODE REVIEW

**Comment by AnonXS** [comment]
SCRIPT_COMMAND_SET_FACING - 36?

**Comment by miraco** [comment]
Isnt SCRIPT_COMMAND_SET_FACING  just for creature x facing creature y?

**Comment by AnonXS** [comment]
well poke @killerwife  if a command should have more usability, he usually finds a way to make it work with all theunit/npc/player rewrites that are ongoing.

as we normally want every command to be unit level pretty much.

**Comment by Grz3s** [comment]
why dont you just look at wiki.. its all explained well there:
```code
 3 SCRIPT_COMMAND_MOVE_TO   resultingSource = Creature
     If position is very near to current position, or x=y=z=0, then only orientation is changed
     If x=y=0 and z !=0, then only Z position is changed (new value will be added to current 'z' position)
     * datalong = dbscripts_on_relay id - executed for source and target same as this script
     * datalong2 = travel_speed*100 (use 0 for creature default movement)
     * datalong3 = enum ForcedMovement
     * data_flags & SCRIPT_FLAG_COMMAND_ADDITIONAL: teleport unit to position 
     * x/y/z/o
```
and
```
36 SCRIPT_COMMAND_SET_FACING                Turn resultingSource towards resultingTarget
     * resultingSource = Creature, resultingTarget WorldObject
     * data_flags & SCRIPT_FLAG_COMMAND_ADDITIONAL also set TargetGuid of resultingSource to resultingTarget.
     In this case resultingTarget MUST be Creature/ Player
     * datalong != 0 Reset TargetGuid, Reset orientation
```
So:
if u want static orientation change to exact spot use command 3 with x/y/z = 0 and o = your value
if u want npc turn to player or any other dynamic object - use command 36 with correct target set.

**Comment by killerwife** [comment]
I will reply to this in a few hours when I am home :P I believe I have some unexported shit for exactly this.

**Comment by al3xc1985** [comment]
@Grz3s  nice to see you man, nice to see you again!

**Comment by killerwife** [comment]
@miraco what @Grz3s said. Basically if you do a MoveTo command with xyz 0 and only orientation set, it will only change orientation.

**Comment by miraco** [comment]
I normaly agree with AnonXS, each command being a unit level is nice. 
But for me, movement and orientation change is the same, so having command 3 for both is okay for me.

I updated the file and removed xyz coords.

**Pull request merged**
