### PR TITLE
Patrol Shedules Quest End Script

### PR DESCRIPTION
**Pull request by miraco**
Care this is still not working as it should, and i only opened it as pr already cause im running into some issues im not rly sure how to deal with.

Quest[ Patrol Shedules](https://tbc.wowhead.com/quest=330/patrol-schedules#comments:id=106124)

After completing this quest, the spy  'privat merle' reveals and does a small event.
- runs into the camp
- on waypoint reach he turns to the player that finished the quest.
- Text: 'Curse you, $N!  One day, vengeance will be mine' with Player as target for $N.
- Changes faction
- Starts running to duskwood
- Spawns 3 Plaque Spreader

Then multiple things can happen:
_All plaque spreader gets killed:_
Privat Merle keeps moving and despawns after some seconds
https://youtu.be/4FjtaO9DNU4 

_Privat Merle gets killed_
Plaque Spreader moving back to their spawn and despawn
https://youtu.be/ovxaxRjo5YU

since he changes the faction its possible that privat merle and [rebel watchmen](https://tbc.wowhead.com/npc=754/rebel-watchman) can start a fight.

Whats missing currently:

- [x] The faction privat merle changes to (its not in current sniffs i have)
- [x] Privat merle is not facing/targeting player for text
- [x] Plaque Spreader should be a spawn_group and use formation for their movement.
- [x] Not sure on which waypoint the Plaque spreader get spawned

### CODE REVIEW

**Comment by insunaa** [comment]
Tiny correction: They're probably Plague Spreaders, not Plaque Spreaders. Plaque is the stuff that accumulates on your teeth if you don't brush them (or a plate with text on it)

**Comment by killerwife** [comment]
Okay so, the plague spreader thingy. They should be a spawn_group with worldstate condition set. I plan to add (very) soon™ one thing for this: setting worldstate variable in dbscripts, so you can spawn that group by setting it to a different value.

**Comment by miraco** [comment]
Yeah that’s  what I was hoping for

**Comment by miraco** [comment]
Update the script for now. Thanks to KW i managed to spawn the group via worldstate and have it in spawn_group for right formation movement.

Still have to find the right factions for privat merle/plaque spreaders and let them fight each other.

**Comment by AnonXS** [comment]
grafik

he always gets killed by this guy?

**Comment by miraco** [comment]
Yes and no.
They always attack each other but I also saw him winning the fight(on ptr) so maybe have to recheck npc stats 
But it is always a close fight

**Comment by AnonXS** [comment]
```
>	mangosd.exe!std::_Tree_unchecked_const_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const ,unsigned int>>>,std::_Iterator_base0>::operator++() Line 51	C++
 	mangosd.exe!std::_Tree_unchecked_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<unsigned int const ,unsigned int>>>>::operator++() Line 144	C++
 	mangosd.exe!CreatureGroup::Despawn() Line 447	C++
 	mangosd.exe!SpawnGroup::Spawn(bool force) Line 129	C++
 	mangosd.exe!SpawnGroup::Update() Line 71	C++
 	mangosd.exe!CreatureGroup::Update() Line 428	C++
 	mangosd.exe!SpawnManager::Update() Line 167	C++
 	mangosd.exe!Map::Update(const unsigned int & t_diff) Line 682	C++
 	mangosd.exe!MapUpdateWorker::execute() Line 53	C++
 	mangosd.exe!MapUpdater::WorkerThread() Line 98	C++
 	[External Code]	````

When the ghouls "should" despawn, server crashes for me.

**Comment by miraco** [comment]
never had his crash before, but ill look at it

**Comment by miraco** [comment]
I updated the file now and the crash should be gone. it happend cause of SPAWN_GROUP_DESPAWN_ON_COND_FAIL 

I rechecked health and level, that is fine in our db. not sure about armor/damage.

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/80ee3d5fe34b5e682ca29fc59c6974bcd3e2328a

**Pull request closed without merging**
