### PR TITLE
DM West: improve (patrolling) spawns.

### PR DESCRIPTION
**Pull request by evil-at-wow**
For anyone who has seen the original, the state of Dire Maul West is less than ideal. In particular, there are two major shortcomings that, once fixed, would make a huge difference:
* Almost everything in Immol'thar's room is static rather than moving, and quite a few spawns are off.
* Apart from one, Eldreth Spectre spawns aren't moving either. Several spawns are also missing.

So I've started an effort to do exactly that.

Unfortunately, my own capture archive doesn't provide all the necessary data - many of the paths are incomplete.
So before I turn to a best effort based on incomplete paths augmented with guesswork from videos I have collected, I'd like to check if there's anyone that can provide the missing data (so tagging @Grz3s @miraco @insunaa). For now I'm interested in the paths of [Arcane Torrent](https://www.wowhead.com/tbc/npc=14399/arcane-torrent), [Eldreth Spectre](https://www.wowhead.com/tbc/npc=11473/eldreth-spectre) and [Residual Monstrosity](https://www.wowhead.com/tbc/npc=11484/residual-monstrosity). Note that spawns have changed in later versions so I'm looking for at most WoTLK data (I don't know when exactly they were changed, but the Cataclysm tuning sweep would be my guess. I know for sure that 5.4 has different/reduced spawns).

### CODE REVIEW

**Comment by Grz3s** [comment]
Ive got myself that last month of wotlk classic .. time to gather  as much data as i can .. so whats req here, will also be collected.
Just be patient

**Comment by al3xc1985** [comment]
I am gathering data 2, so be patient. U will have it all :D

**Comment by evil-at-wow** [comment]
I'm patient, no worries! Take all the time you need. Thank you in advance, much appreciated!

Also, just to potentially save you some trouble al3xc1985: I'm not looking for videos here. I have clear videos already, and I can use those to make very good 'guesses' about all the paths needed. The only thing that's even better is the actual waypoint data, so that's the only thing I'm looking for right now (but I'm not sure that's what you meant, hence my clarification).

**Comment by al3xc1985** [comment]
I can record all the mobs with all the waypoints.
Isn't that good for you?

**Comment by al3xc1985** [comment]
I found that  Eldreth Spectre have waypoints, but I do not have currently how to detect them, but I run a way from one, and followed him back and saw for a short time until resthealted that he has waypoints.
Also I saw that some others in a few runes, were found in different locations

**Comment by al3xc1985** [comment]
https://youtu.be/IIFtvBOeJ7Y

**Comment by killerwife** [comment]
> I found that Eldreth Spectre have waypoints, but I do not have currently how to detect them, but I run a way from one, and followed him back and saw for a short time until resthealted that he has waypoints. Also I saw that some others in a few runes, were found in different locations

you can use invis pots

**Comment by al3xc1985** [comment]
well, can't my server is almost dead, I can't find any. I will do an other trick. I shall move my char to a free and high pop server before cata starts

**Comment by evil-at-wow** [comment]
Another option that works great is to use a warlock's "Detect invisibility" if you have one or - less practical, because it only lasts for 10m - one is willing to buff you with it.

Thanks for the effort already! I don't see sniffs for West in that link (I got all the other ones), but I suspect that's expected at this point.

**Comment by al3xc1985** [comment]
Ups sorry

https://fileport.io/hkFCzQM57V6H

This is for West.
I don;t have anyone to help me out. but don;t worry. 
I'l manage it

**Comment by al3xc1985** [comment]
If I can't manage it, I am starting a new char on classic part, a hunter, and I shall the alchemy and see what I can do with some invis potions

**Comment by cpevors** [comment]
If no one says it, thank you, Alex. Your willingness to comb through the nitty gritty and help nail down concrete data makes this project that much better.

**Comment by al3xc1985** [comment]
As I said, I have list with all dungeons/zones/cities almost done for the classic part:
-emotes
-mobs/npcs paths
- a lot of RP's
-  gameobjects
- loot
- spawns missing
- game mechanics
- mobs/npc equipments
- etc
Does not have yet:
-raids
- quests


For the last part I don;t have much time left on wotlk, BUT I am planning to continue on classic realms with a hunter (best for such jobs on classic) and do:
- ALL GAME classic quests Alliance + horde
- Get as much data possible about the raids mobs/npc's mechanincs paths, etc

And than move on to TBC and WoTLK part to shoot them all. This is going to be easier in cata, cause I will have gear, and can see even raids in TBC and WoTLK much better. As far as I know, they weren't touched in cata, only the classic part Azeroth part was modified

**Comment by al3xc1985** [comment]
https://youtu.be/1gCE-XsYRKc

**Comment by evil-at-wow** [comment]
That's awesome, thanks a lot for that! And warlocks rule! I got the files, now it's a matter of extracting what I was looking for in the days and week ahead, but that's again on me. Stay tuned!

**Comment by al3xc1985** [comment]
Anyone can ask for anything, their wish shall be granted! I am like a gennie in Wow

**Comment by evil-at-wow** [comment]
I have - finally! - picked this up again and as you can see I've pushed my latest updates. Those complete the mobs and paths as mentioned in the commits with the data I currently have.

Again a big thank you to al3xc1985 for making this happen! Your data allowed me to reconstruct almost everything perfectly, even though it was at times a bit of a puzzle with paths not fully repeating or extra movement because of combat.

There are two paths that are incomplete (I've marked them with a comment in the SQL). It's probably just one point or so missing. One is because of aggro before the end of the path (see the associated video at https://youtu.be/1gCE-XsYRKc?t=2082), the other is because you probably weren't close enough at the time. But that's not a big deal. I could even add them with some guesswork but I've actually opted not to do that because 1) it's just a short distance missing so no big deal and 2) it avoids confusion later when people check points against other/more data (the things that are here now should be 100% correct).

Feel free to test ingame!

**Comment by cpevors** [comment]
Definitely 'feels' better than before!

**Comment by al3xc1985** [comment]
Evil, don't worry. I did that dungeon several timea and I am sure I can remember what is missing. I will be able to help withbthat 2.

My question is, what dungeon do u want next? And u shall have it

**Comment by evil-at-wow** [comment]
I appreciate the offer, but let's not think about that next dungeon just yet. There's still quite a few things to do in Dire Maul for now besides those Arcane Torrent and Eldreth Spectre NPCs!

**Comment by al3xc1985** [comment]
Ok, checked that point, and I do remember that I know it. I shall keep that in mind and ckeck it with my hunter on 60

**Comment by AnonXS** [comment]
I think it's time to get this merged, no matter if it is 100% complete or still just an improvement as it improves the situatoin already alot, if you have outstanding guids/issues that need to be resolved you can just place them as comments in the header file of the instance file.

https://github.com/cmangos/tbc-db/pull/1200/files#diff-de3aeb7b0aa61382ee118bb90322278b138e42d5c811dc4dc1b2372f219495ceL10

**Comment by evil-at-wow** [comment]
Fair enough @AnonXS, seeing the two commits are basically finished on their own and I likely won't have time to make more updates to this in the next few weeks. I can always open a new PR with more updates later!

If you're willing to do a review here, please be my guest. The two remaining comments I have for this PR - incomplete paths - were already marked with a comment in the respective paths (see commits), and I feel that's a better place for a comment than the header section where it's harder to refer to the precise part that's missing.

**Comment by AnonXS** [comment]
https://github.com/cmangos/tbc-db/commit/930f7b9e72e3939ab77eb43a43612ca1d1eec9c7

**Comment by al3xc1985** [comment]
Lovely!

**Pull request closed without merging**
