### PR TITLE
Fixed some AV quest aquisition; Removed old inaccessible AV quests

### PR DESCRIPTION
**Pull request by martindev446**
## Removed in 1.8.0
* The following quests have been disabled, as they were [removed from the game in patch 1.8.0](https://wow.gamepedia.com/Patch_1.8.0#PvP). In the name of accuracy, the reputation reward values have been corrected anyway in the DB. 
  * _Note: setting Method = 1 in quest_template does not prevent the quest from being accepted from the NPC, so I had to remove them from creature_questrelation instead. Let me know if this isn't acceptable._

Quest name | entry | faction
-|-|-
Korrak the Everliving | 7382 | Alliance
Korrak the Bloodrager | 7202 | Alliance
The Legend of Korrak | 7181 | Horde
The Return of Korrak | 7381 | Horde

## Alterac Valley reputation trinket quests:
* These Alterac Valley trinket quests:
  * Must now be completed in-order
  * Require the appropriate level of reputation to accept and complete
  * Reward the correct reputation
  * Require the correct race(Alliance/Horde)
  * Are marked as non-repeatable
### Horde: Warmaster Laggrond _(entry 13840)_
Quest Name | ID | Rep Required
-|-|-
Proving Grounds | 7161 | Neutral
Rise and be Recognized | 7163 | Friendly
Honored amongst the clan | 7164 | Honored
Earned Reverence | 7165 | Revered
Legendary Heroes | 7166 | Exalted
The Eye of Command | 7167 | Full Exalted (999/1000)

### Alliance: Lieutenant Haggerdin _(entry 13841)_
Quest Name | ID | Rep Required
-|-|-
Proving Grounds | 7162 | Neutral
Rise and be Recognized | 7168 | Friendly
Honored Amongst the Guard | 7169 | Honored
Earned Reverence | 7170 | Revered
Legendary Heroes | 7171 | Exalted
The Eye of Command | 7172 | Full Exalted (999/1000)

### North
gameobject_template entry | name
-|-
179436 | [PH] Horde A1 Tower Pre-Banner BIG
178927 | [PH] Alliance A1 Tower Banner BIG

### South
gameobject_template entry | name
-|-
178955 | [PH] Horde H1 Tower Banner BIG
179446 | [PH] Alliance H1 Tower Pre-Banner BIG

## Fixed quest objectives for Horde and Alliance quest(s): "Proving Grounds"
* Gameobject quest objectives "Frostwolf Banner" and "Stormpike Banner" now correctly appear.

### CODE REVIEW

**Comment by martindev446** [comment]
I think I did the PR correctly this time. Otherwise, let me know and I'll fix it

**Comment by AnonXS** [comment]
looks good, now you can rebase your forks/branch and update this remote branch

**Comment by AnonXS** [comment]
you didnt rebase correctly.

**Comment by martindev446** [comment]
Yeah i figured something was wrong. What are the proper commands i should use to rebase?  

This is what i did:
```
git checkout alteracvalley 
git rebase upstream/master
```
At first I thought I did it correctly, but then the Github desktop client wouldnt let me push to my fork without doing a merge.

**Pull request closed without merging**
