### PR TITLE
Fix commemorative plaques

### PR DESCRIPTION
**Pull request by Supermarco333**
I tried to fix the orientation/position of those plaques. The result isn't perfect but still better than currently.

### CODE REVIEW

**Comment by killerwife** [comment]
@Supermarco333 please give me gameobject_template entries for these :) I will supplement your PR with sniff data.

**Comment by Supermarco333** [comment]
- GUID: 20458 --> ENTRY: 177200
- GUID: 20459 --> ENTRY: 177202
- GUID: 31619 --> ENTRY: 177201

**Comment by Supermarco333** [comment]
Just wondering, where do you sniff the data ?

**Comment by killerwife** [comment]
BFA and classic. But also old data.

**Comment by killerwife** [comment]
Please review this if its an improvement:
DELETE FROM gameobject WHERE Id IN(177200,177202,177201) AND guid IN(20458,20459,31619);
INSERT INTO gameobject(guid, id, map, spawnMask, position_x, position_y, position_z, orientation, rotation0, rotation1, rotation2, rotation3, spawntimesecsmin, spawntimesecsmax, animprogress, state) VALUES
('20458', '177200', '0', '1', '-8337.724', '519.8453', '122.939224', '-1.1194002628326416', '-0.66757154', '-0.23312569', '-0.66757107', '0.23312989', '120', '120', '100', '1'),
('31619', '177201', '0', '1', '-8338.468', '509.13562', '122.93091', '0', '-0.307199', '-0.63688946', '-0.30719852', '0.6368906', '120', '120', '100', '1'),
('20459', '177202', '0', '1', '-8347.636', '520.9723', '122.939224', '0', '-0.307199', '-0.63688946', '-0.30719852', '0.6368906', '120', '120', '100', '1');

**Comment by Supermarco333** [comment]
This fix is better than everything I could have ever tried. ^^

Still, you absolutely need to execute:
DELETE FROM `game_event_gameobject` WHERE `guid` IN (31619);
Otherwise, 31619 will only spawn during Brewfest.

Although, it's a really tiny little detail but if you want to be perfect, just do a pi rotation with 31619 around z-axis.

**Pull request closed without merging**
