### PR TITLE
[Quest] Add complete script for quest Samophlange

### PR DESCRIPTION
**Pull request by miraco**

### CODE REVIEW

**Comment by miraco** [comment]
Based on PTR sniffs and Video.
Only thing thats currently missing, before the gameobject gets despawned, it should also cast the spell.
https://youtu.be/aCUt4AijgY4 

Not sure how to handle this.
Maybe you know something: @killerwife  @AnonXS 


`ServerToClient: SMSG_SPELL_START (0x2C3A) Length: 107 ConnIdx: 1 Time: 02/17/2022 13:08:58.401 Number: 634
(Cast) CasterGUID: Full: 0x204CB00020035C80001FA3000005659D Creature/0 R4908/S8099 Map: 1 Entry: 3442 Low: 353693
(Cast) CasterUnit: Full: 0x204CB00020035C80001FA3000005659D Creature/0 R4908/S8099 Map: 1 Entry: 3442 Low: 353693
(Cast) CastID: Full: 0xBC4CB000200D67C3001FA300000E3ADB Cast/3 R4908/S8099 Map: 1 Low: 932571
(Cast) OriginalCastID: Full: 0x0
(Cast) SpellID: 13727 (13727)
(Cast) SpellXSpellVisualID: 244586
(Cast) CastFlags: 2
(Cast) CastFlagsEx: 1048576
(Cast) CastTime: 0
(Cast) (MissileTrajectory) TravelTime: 0
(Cast) (MissileTrajectory) Pitch: 0
(Cast) DestLocSpellCastIndex: 0
(Cast) (Immunities) School: 0
(Cast) (Immunities) Value: 0
(Cast) (Predict) Points: 0
(Cast) (Predict) Type: 0
(Cast) (Predict) BeaconGUID: Full: 0x0
(Cast) HitTargetsCount: 0
(Cast) MissTargetsCount: 0
(Cast) MissStatusCount: 0
(Cast) RemainingPowerCount: 0
(Cast) HasRuneData: False
(Cast) TargetPointsCount: 0
(Cast) HasAmmoDisplayId: False
(Cast) HasAmmoInventoryType: False
(Cast) (Target) Flags: 0 (Self)
(Cast) (Target) HasSrcLocation: False
(Cast) (Target) HasDstLocation: False
(Cast) (Target) HasOrientation: False
(Cast) (Target) hasMapID : False
(Cast) (Target) Unit: Full: 0x0
(Cast) (Target) Item: Full: 0x0
(Cast) (Target) Name: 

ServerToClient: SMSG_SPELL_GO (0x2C39) Length: 121 ConnIdx: 1 Time: 02/17/2022 13:08:58.401 Number: 635
(Cast) CasterGUID: Full: 0x204CB00020035C80001FA3000005659D Creature/0 R4908/S8099 Map: 1 Entry: 3442 Low: 353693
(Cast) CasterUnit: Full: 0x204CB00020035C80001FA3000005659D Creature/0 R4908/S8099 Map: 1 Entry: 3442 Low: 353693
(Cast) CastID: Full: 0xBC4CB000200D67C3001FA300000E3ADB Cast/3 R4908/S8099 Map: 1 Low: 932571
(Cast) OriginalCastID: Full: 0x0
(Cast) SpellID: 13727 (13727)
(Cast) SpellXSpellVisualID: 244586
(Cast) CastFlags: 256
(Cast) CastFlagsEx: 1048592
(Cast) CastTime: 127265432
(Cast) (MissileTrajectory) TravelTime: 0
(Cast) (MissileTrajectory) Pitch: 0
(Cast) DestLocSpellCastIndex: 0
(Cast) (Immunities) School: 0
(Cast) (Immunities) Value: 0
(Cast) (Predict) Points: 0
(Cast) (Predict) Type: 0
(Cast) (Predict) BeaconGUID: Full: 0x0
(Cast) HitTargetsCount: 1
(Cast) MissTargetsCount: 0
(Cast) MissStatusCount: 0
(Cast) RemainingPowerCount: 0
(Cast) HasRuneData: False
(Cast) TargetPointsCount: 0
(Cast) HasAmmoDisplayId: False
(Cast) HasAmmoInventoryType: False
(Cast) (Target) Flags: 2048 (GameObject)
(Cast) (Target) HasSrcLocation: False
(Cast) (Target) HasDstLocation: False
(Cast) (Target) HasOrientation: False
(Cast) (Target) hasMapID : False
(Cast) (Target) Unit: Full: 0x0
(Cast) (Target) Item: Full: 0x0
(Cast) (Target) Name: 
(Cast) [0] HitTarget: Full: 0x2C4CB000209E3A00001FA300000E3AD5 GameObject/0 R4908/S8099 Map: 1 Entry: 162024 Low: 932565`

**Comment by killerwife** [comment]
13727 has TARGET_GAMEOBJECT_SCRIPT_NEAR_CASTER

which means make creature cast it and add spell_script_target entry based  on documentation

**Comment by miraco** [comment]
Thats how its done currently, added spellscript target and let the creature cast the spell.

**Comment by killerwife** [comment]
What spell should the go use? Nothing in your excerpt about that

**Comment by killerwife** [comment]
Also its a dummy spell, so any behavior must be added as a small spellscript. I can help u if u gimme details what should happen after the spell hits

**Comment by miraco** [comment]
Thats the problem, i couldnt find anything in any of my sniffs about this. Only have this on video.
https://youtu.be/aCUt4AijgY4?t=19

You can see the gameobject have some explosion effect before respawning. I thought that it got triggert threw the spell that npc casts.

Ill resniff this on ptr when i have time

**Comment by miraco** [comment]
I resniffed this quest today on retail tbc. Nothing to find. Only thing whats happening is:

Gameobject (id 162024) gets spawns 
npc turns to object and use emote,
npc cast spell (13727) on object
object gets destroyed.

No extra spell for the explosion animation before despawning.

**Pull request closed without merging**
