### PR TITLE
fix capitalization issues

### PR DESCRIPTION
**Pull request by hlarsen**
a few more fixes for table names

### CODE REVIEW

**Comment by killerwife** [comment]
Is this all changes needed to make it run in strict mode?

**Comment by ulfgebhardt** [comment]
i get the same errors and its cuz of the storage method. Linux stores files case-sensitive. Therefore Tablenames are case-sensitive.

More here:
http://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html

**Comment by killerwife** [comment]
I should update my server I think.....

**Comment by ulfgebhardt** [comment]
Its a linux thingy, if u use windows, u wont get that error for tables, triggers and databases - if u use linux this should always be the case. Could u also update the Loot References? Pretty please <3

**Comment by killerwife** [comment]
Yes its on my TODO list, but as I neglected vengeance for the past 3 weeks due to exporting these changes, I have to do a lot of cleanup atm. Will do it whenever I have time.

**Comment by ulfgebhardt** [comment]
vengeance is ur server? Nice ;-)

**Comment by killerwife** [comment]
Yes, and these are all vengeance changes, all the 600+ commits I added. (ofc some being backports)

**Comment by killerwife** [comment]
Ty, merging.

**Pull request merged**
