### PR TITLE
Karazhan - start adding moving creature groups into spawn_group

### PR DESCRIPTION
**Pull request by miraco**
This is a work in Progress atm.

### CODE REVIEW

**Comment by miraco** [comment]
_**2 Groups with linear movement**_
grp1
grp2

_**2 Groups with side by side movement**_

grp3
grp4

2 Groups with ? movement (have to check what we have to use here i guess its SPAWN_GROUP_FORMATION_TYPE_FANNED_OUT_BEHIND
grp5



Possible that the groups are also a spawn_group (still need to get added then)
grp6

Also recheck FormationSpread for all groups and remove pooling for gameobjects (do it via spawn_group)

**Comment by miraco** [comment]
I researched a bit for Sealed Tome.
There are 11 Sealed Tomes with type 3 (chest) and loot in the database, and 5 with type 5 (trap)
`select entry, displayId from gameobject_template where name = "Sealed Tome" AND type = 3;
+--------+-----------+
| entry  | displayId |
+--------+-----------+
| 181768 |       558 |
| 181833 |      4135 |
| 181837 |       417 |
| 181839 |       338 |
| 181841 |      3731 |
| 181843 |       430 |
| 181845 |      6894 |
| 181846 |      6893 |
| 181847 |      6891 |
| 181848 |      6892 |
| 184847 |         0 |
+--------+-----------+
11 rows in set

mysql> select entry, displayId from gameobject_template where name = "Sealed Tome" AND type = 6;
+--------+-----------+
| entry  | displayId |
+--------+-----------+
| 181831 |      2770 |
| 181838 |      2770 |
| 181840 |      2770 |
| 181842 |      2770 |
| 181844 |      2770 |
+--------+-----------+
5 rows in set`

Unbenannt

Im not 100% sure about how blizzard is doing it but my biggest guess is:
All 5 books in this picuture can get clicked
1 book = 1 spawn_group with all 16 (maybe 15 one without displayid) entrys in spawn_group_entry

**Comment by miraco** [comment]
> 

I sniffed it now 4 times, with 4 different chars.
I had 41 tome spawns in every sniff.
First Sniff
181847, 181845, 181846, 181848, 181768: gobs with loot 39
181833, 181837, 181839, 181841, 181843: gobs with traps 2

2ndSniff
181847, 181845, 181846, 181848, 181768: gobs with loot 35
181833, 181837, 181839, 181841, 181843: gobs with traps 6

3rd Sniff
181847, 181845, 181846, 181848, 181768: gobs with loot 37
181833, 181837, 181839, 181841, 181843: gobs with traps 4

4th Sniff
181847, 181845, 181846, 181848, 181768: gobs with loot 32
181833, 181837, 181839, 181841, 181843: gobs with traps 9

**Comment by AnonXS** [comment]
ok 41 with weighting heavly against traps, but there are prob also groups, e.g some around fire etc certain locations.

**Comment by miraco** [comment]
Yes in all 4 tests i had always 5 tomes on the balcony below aran entrance, so i guess this is atleast 1 spawn_group. But im currently trying to inport all spawns, and i want to have atleast 10 different sniffs to have a good result before updating sql.

**Comment by AnonXS** [comment]
yea that's reasonable, we respawned dungeons also with 10x versions this time to get more different spawn possibilities (creature_spawn_entry)

so the more input we can get, the better we can compose groups.

**Comment by miraco** [comment]
Okay so this is my research now:
24 different groups.

grp1
grp2
grp3
grp4
grp5
grp6
grp8
grp9
grp10
grp11
grp12
grp13
grp14
grp15
grp16
grp17
grp18
grp19
grp20
grp21

Active means how many of this spawnpoints will be active.

I just dont know if there are any static spawns or if all of them can be random. But my biggest guess is that they can all be rnd.

**Comment by miraco** [comment]
Gameobjects added for now. 90 % chance for loot, 10% chance for trap.

But this shouldnt be merged for now. I just noticed that the "followers" in these groups keep respawning even if boss is dead. Will need to use worldstate for this i guess. And if i have to use worldstate/conditions anyway ill at somepoint set all groups into a spawn_group to get correct linkings/boss linking.

**Comment by miraco** [comment]
I'll close this for now, cause this needs much more time and work to get this done correctly.
For example we miss some spawns/ need to correct spawns 
Will do it if I have some more time

**Pull request closed without merging**
