### PR TITLE
[ACID] add 'Captured Totem Test Credit' spell to Mottled Drywallow Cr…

### PR DESCRIPTION
**Pull request by miraco**
…ocolisk and Drywallow Daggermaw

This should fix quest [The Grimtotem Weapon](https://tbc.wowhead.com/quest=11169/the-grimtotem-weapon)

*Care kill credit still dont given, not sure why. spell is casted correctly on death

### CODE REVIEW

**Comment by miraco** [comment]
i did some more tests with this:
When creature casts the spell every 2 seconds on enemy target, you get quest credits.
when using event_type 6 (on death) without condition, and no totem spawned, the creature casts the spell on player (you see the visual) but you dont get quest credit.

**Comment by AnonXS** [comment]
grafik

this triggered skull spell seems to be the thing broken?

**Comment by AnonXS** [comment]
Keeping this open until the underlying core issue is resolved.

**Comment by miraco** [comment]
This quest is fixed, afaik kw did it with a core change.

Works now.

**Pull request closed without merging**
